spring:
  application:
    #应用名称
    name: service-sms

#mybatis配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
    #,http://localhost:7901/eureka/,http://localhost:7902/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30


---
spring:
  profiles: v1

eureka:
  instance:
    metadata-map:
      # 以下内容是自定义的 K V，可以通过eureka http post修改
      version: v1
      a: a1
server:
  #服务端口
  port: 8003
---
spring:
  profiles: v2

eureka:
  instance:
    metadata-map:
      version: v2
server:
  #服务端口
  port: 8004
